/*
===========================================
E-Commerce SQL Analysis Project
Author: Roshni Yadav
Description:
Business analysis on an e-commerce database
using SQL joins, aggregations, and reporting.
===========================================

===========================================
E-COMMERCE SQL ANALYSIS PROJECT
===========================================

===========================================
CUSTOMER ANALYSIS
===========================================
*/

-- Q1. Show all customers from Mumbai
SELECT *
FROM customers
WHERE city = 'Mumbai';

-- Q2. Show all delivered orders
SELECT *
FROM orders
WHERE status = 'Delivered';

-- Q1. Show all customers from Mumbai
SELECT * FROM customers
WHERE city = "Mumbai";

-- Q2.status Show all delivered orders
SELECT * FROM orders
WHERE status = "Delivered";

-- Q3. Products with price above 1000
SELECT * FROM products
WHERE price > 1000;

-- Q4. Find the highest product price.
SELECT MAX(price) FROM products;

-- Q5. Count products in each category.
SELECT category,
  COUNT(product_name) as number_of_product
FROM products
GROUP BY category;

-- Q6. Find average product price by category.
SELECT category,
AVG(price) as avg_price
FROM products
GROUP BY category;

-- Q7. Find categories having more than 10 products.
SELECT category,
COUNT(product_name) as Number_of_Product
FROM products
GROUP BY category
HAVING Number_of_Product > 10;

-- Q8. Find most used payment method
SELECT payment_method ,
COUNT(*) as no_of_payment
FROM orders
GROUP BY payment_method
ORDER BY no_of_payment DESC;

-- Q9. Count orders placed each month
SELECT MONTH(order_date) AS OrderMonth,
       COUNT(order_id) AS TotalOrders
FROM orders
GROUP BY MONTH(order_date)
ORDER BY OrderMonth;

-- Q10. Find average number of orders per month.
SELECT MONTH(order_date) AS month,
AVG(order_id) AS avg_order
FROM orders
GROUP BY MONTH(order_date);

-- Q11. Find categories whose average product price is above ₹2000.
SELECT category,
AVG(price)
FROM productS
GROUP BY category
HAVING AVG(price) > 2000;

-- Q12. List all customers and orders
SELECT c.name,
  count(o.order_id) as totalorder
FROM customers c
inner join orders o
on c.customer_id = o.customer_id
GROUP BY c.name
ORDER BY totalorder DESC;

-- Q13. Revenue earned from each product category.
SELECT p.category,
 ROUND(SUM(oi.quantity * oi.unit_price),2) AS revenue
FROM products p
inner join order_items oi
ON p.product_id = oi.product_id
GROUP BY p.category
ORDER BY revenue DESC;

-- Q14. Calculate total revenue generated by each customer.
SELECT c.name,
    SUM(oi.quantity * oi.unit_price) AS revenue
FROM customers c
join orders o
ON c.customer_id = o.customer_id
join order_items oi
ON oi.order_id = o.order_id
GROUP BY c.name
ORDER BY revenue DESC;

-- Q15. Find customers who have never placed an order.
SELECT c.name,
       o.order_id
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;

-- Q16. Average product rating per category.
SELECT p.category,
  ROUND(AVG(r.rating),2) AS avg_rating ,
  COUNT(r.review_id) AS review
FROM products p 
JOIN reviews r
ON p.product_id = r.product_id
GROUP BY p.category
ORDER BY avg_rating DESC;

-- Q17. Monthly revenue trend
 SELECT DATE_FORMAT(order_date, '%Y-%m') AS month, ROUND(SUM(total_amount), 2) AS monthly_revenue
 FROM orders
 WHERE status = 'Delivered'
 GROUP BY month
 ORDER BY month;
 
-- Q18. Find customers who purchased products but never reviewed them.
SELECT DISTINCT c.customer_id,
      c.name,
     r.review_id
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
LEFT JOIN reviews r
ON c.customer_id = r.customer_id
WHERE  r.review_id IS NULL;

-- Q19. Top 10 highest spending customers
SELECT c.customer_id,
      c.name,
      c.city,
     SUM(o.total_amount) AS spending
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
WHERE o.status = "Delivered"
GROUP BY c.customer_id,c.name,c.city
ORDER BY spending DESC
limit 10;

-- Q20. Find products that generate high revenue but have low ratings.
SELECT p.product_name,
   SUM(oi.quantity * oi.unit_price) AS revenue,
   AVG(r.rating) AS rating
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
LEFT JOIN reviews r
ON r.product_id = p.product_id
GROUP BY p.product_name
HAVING AVG(r.rating) <
(
    SELECT AVG(rating)
    FROM reviews
)
ORDER BY rating DESC;

-- Q21. Monthly Sales Report.
SELECT YEAR(o.order_date) AS OrderYear,
     MONTH(o.order_date) AS OrderMonth,
     COUNT(DISTINCT o.order_id) AS UniqueOrder,
     SUM(oi.quantity * oi.unit_price) AS Revenue,
     COUNT(DISTINCT o.customer_id) AS UniqueCustomer
FROM orders o
INNER JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY OrderYear , OrderMonth
ORDER BY OrderYear , OrderMonth;
 
-- Q22. Customer Performance Report.
SELECT c.name AS CustomerName,
	COUNT(DISTINCT o.order_id) AS TotalOrder,
    SUM(oi.quantity * oi.unit_price) AS TotalRevenue,
    ROUND(SUM(oi.quantity * oi.unit_price) / COUNT(DISTINCT o.order_id), 2) AS AvgOrderValue
FROM customers c
JOIN orders o 
ON c.customer_id = o.customer_id
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY CustomerName,
         c.customer_id
ORDER BY TotalRevenue DESC;

-- Q23. Product Performance Report.
SELECT p.product_name,
    SUM(oi.quantity) AS TotalQuantitySold,
    SUM(oi.quantity * unit_price) AS TotalRevenue,
    AVG(r.rating) AS AvgRating,
    COUNT(r.review_id) AS Reivews
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id 
LEFt JOIN reviews r
ON p.product_id = r.product_id
GROUP BY p.product_name,p.product_id
ORDER BY TotalRevenue;

-- Q24. Category Performance Report.
SELECT p.category,
     SUM(oi.quantity) AS TotalProductSold,
     SUM(oi.quantity * oi.unit_price) AS TotalRevenue,
     AVG(r.rating) AS AvgRating
FROM products p 
JOIN order_items oi 
ON p.product_id = oi.product_id
LEFT JOIN reviews r
ON p.product_id = r.product_id
GROUP BY p.category
ORDER BY TotalRevenue DESC;

-- Q25.Customer Engagement Report.
-- Requirements: Customer Name, Total Orders, Total Reviews Given,Total Revenue Generated, Last Purchase Date
SELECT c.name AS CustomerName,
       COUNT(DISTINCT o.order_id) AS TotalOrder,
       COUNT(DISTINCT r.review_id) AS TotalReview,
       SUM(oi.quantity * oi.unit_price) AS TotalRevenue,
       MAX(o.order_date) AS LastPurchaseDate
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN order_items oi
ON o.order_id = oi.order_id
LEFT JOIN reviews r
ON c.customer_id = r.customer_id
GROUP BY c.name,c.customer_id
ORDER BY TotalRevenue DESC;
       
